ModelParams = dict(
    extra_mark='endonerf',
    camera_extent=10,
)

OptimizationParams = dict(
    coarse_iterations=1000,
    iterations=9000,
    deformation_lr_init=0.00016,
    deformation_lr_final=0.0000016,
    deformation_lr_delay_mult=0.01,
    grid_lr_init=0.0016,
    grid_lr_final=0.000016,
    percent_dense=0.01,
    opacity_reset_interval=3000,
    position_lr_max_steps=9000,
    pruning_interval=3000,
)

ModelHiddenParams = dict(
    tracking_type='original',
    endomoeg_expert_hidden_dim=64,
    endomoeg_scaffold_node_count=256,
    endomoeg_scaffold_knn=4,
    endomoeg_scaffold_max_node_offset_ratio=0.02,
    endomoeg_scaffold_max_radius_scale=4.0,
    endomoeg_scaffold_initial_gate_probability=0.05,
    lambda_scaffold_arap=1e-2,
    lambda_scaffold_acceleration=1e-3,
    lambda_scaffold_node_offset=1e-3,
    lambda_scaffold_gate_sparsity=1e-3,
    endomoeg_residual_hard_quantile=0.7,
    endomoeg_residual_preserve_weight=1.0,
    endomoeg_residual_no_regret_weight=2.0,
    endomoeg_residual_no_regret_margin=0.0,
    endomoeg_residual_lr_scale=0.01,
    endomoeg_residual_warmup_iterations=500,
    endomoeg_residual_gradient_clip=0.05,
    endomoeg_residual_max_baseline_psnr_drop=0.05,
    endomoeg_contact_anchor_count=512,
    endomoeg_contact_chart_count=3,
    endomoeg_contact_max_spatial_offset_ratio=0.02,
    endomoeg_contact_max_velocity_ratio=0.05,
    endomoeg_contact_max_acceleration_ratio=0.05,
    endomoeg_contact_max_rotation_radians=0.5,
    endomoeg_contact_max_scale_delta=0.1,
    endomoeg_contact_initial_duration=0.15,
    lambda_contact_bank_sparsity=1e-4,
    lambda_contact_bank_locality=1e-3,
    lambda_contact_bank_acceleration=1e-3,
    lambda_contact_bank_spatial_offset=1e-3,
    lambda_contact_bank_duration=1e-4,
    enable_visibility=True,
    max_disp_smooth_ratio=0.01,
    max_disp_global_ratio=0.01,
    max_disp_local_ratio=0.03,
    max_rot_smooth=0.05,
    max_rot_local=0.05,
    max_scale_smooth=0.05,
    max_scale_local=0.05,
    max_opacity_delta=4.0,

    moe_router_hidden_dim=64,
    endomoeg_router_gaussian_lr=0.05,
    endomoeg_router_feature_lr=0.005,
    endomoeg_min_oracle_headroom=0.3,
    endomoeg_router_gain_temperature=0.02,
    endomoeg_router_lambda_gain=0.1,
    endomoeg_router_lambda_sparsity=1e-3,
    endomoeg_router_lambda_no_regret=0.5,
    endomoeg_router_lambda_dssim=0.2,
    endomoeg_router_gradient_warmup=20,

    endomoeg_joint_router_gaussian_lr=5e-4,
    endomoeg_joint_router_feature_lr=1e-4,
    endomoeg_joint_refinement_lr=5e-6,
    endomoeg_joint_anchor_lambda=1e-3,
    endomoeg_joint_gradient_clip=1.0,
    endomoeg_joint_max_psnr_drop=0.05,

    kplanes_config={
        'grid_dimensions': 2,
        'input_coordinate_dim': 4,
        'output_coordinate_dim': 64,
        'resolution': [64, 64, 64, 100],
    },
    multires=[1, 2, 4, 8],
    defor_depth=0,
    net_width=32,
    plane_tv_weight=0,
    time_smoothness_weight=0,
    l1_time_planes=0,
    weight_decay_iteration=0,
)
