ModelParams = dict(
    extra_mark='endonerf',
    camera_extent=10,
)

OptimizationParams = dict(
    coarse_iterations=1000,
    iterations=9000,
    deformation_lr_init=0.00016,
    deformation_lr_final=0.0000016,
    deformation_lr_delay_mult=0.01,
    grid_lr_init=0.0016,
    grid_lr_final=0.000016,
    percent_dense=0.01,
    opacity_reset_interval=3000,
    position_lr_max_steps=9000,
    pruning_interval=3000,
)

ModelHiddenParams = dict(
    tracking_type='original',
    endomoeg_expert_hidden_dim=64,
    enable_visibility=True,
    max_disp_smooth_ratio=0.01,
    max_disp_global_ratio=0.01,
    max_disp_local_ratio=0.03,
    max_rot_smooth=0.05,
    max_rot_local=0.05,
    max_scale_smooth=0.05,
    max_scale_local=0.05,
    max_opacity_delta=4.0,

    moe_router_hidden_dim=64,
    moe_pixel_router_hidden_dim=32,
    endomoeg_router_gaussian_lr=0.05,
    endomoeg_router_feature_lr=0.005,
    endomoeg_router_pixel_lr=0.005,
    endomoeg_router_oracle_temperature=0.05,
    endomoeg_router_lambda_oracle=1.0,
    endomoeg_router_lambda_starvation=0.01,
    endomoeg_router_lambda_dssim=0.2,
    endomoeg_router_sparse_start=0.5,
    endomoeg_router_gradient_warmup=20,

    endomoeg_joint_router_gaussian_lr=5e-4,
    endomoeg_joint_router_feature_lr=1e-4,
    endomoeg_joint_router_pixel_lr=1e-4,
    endomoeg_joint_global_deformation_lr=1e-6,
    endomoeg_joint_refinement_lr=5e-6,
    endomoeg_joint_anchor_lambda=1e-3,
    endomoeg_joint_gradient_clip=1.0,
    endomoeg_joint_sparse_start=0.25,
    endomoeg_joint_max_psnr_drop=0.05,

    kplanes_config={
        'grid_dimensions': 2,
        'input_coordinate_dim': 4,
        'output_coordinate_dim': 32,
        'resolution': [64, 64, 64, 100],
    },
    multires=[1, 2, 4, 8],
    defor_depth=0,
    net_width=32,
    plane_tv_weight=0,
    time_smoothness_weight=0,
    l1_time_planes=0,
    weight_decay_iteration=0,
)
